DROP DATABASE IF EXISTS CarWashDB;
CREATE DATABASE CarWashDB;
USE CarWashDB;

CREATE TABLE IF NOT EXISTS SEDI (
    ID_Sede INT AUTO_INCREMENT PRIMARY KEY,
    Indirizzo VARCHAR(100) NOT NULL,
    Citta VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTI (
    ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Telefono VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TESSERE (
    Codice CHAR(10) PRIMARY KEY,
    ID_Cliente INT,
    Saldo DECIMAL(10 , 2 ) DEFAULT 0.00,
    ScadenzaAbbonamento DATE NULL,
    FOREIGN KEY (ID_Cliente)
        REFERENCES CLIENTI (ID_Cliente)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS VEICOLI (
    Targa VARCHAR(10) PRIMARY KEY,
    Modello VARCHAR(50),
    Tipo VARCHAR(20),
    ID_Cliente INT,
    FOREIGN KEY (ID_Cliente)
        REFERENCES CLIENTI (ID_Cliente)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IMPIANTI (
    ID_Impianto INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Tipo ENUM('TUNNEL', 'BOX_MANUALE') NOT NULL,
    Stato ENUM('ATTIVO', 'MANUTENZIONE') DEFAULT 'ATTIVO',
    ID_Sede INT NOT NULL,
    FOREIGN KEY (ID_Sede)
        REFERENCES SEDI (ID_Sede)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PROGRAMMI (
    ID_Programma INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Prezzo DECIMAL(10 , 2 ) NOT NULL,
    DurataMinuti INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODOTTI (
    ID_Prodotto INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50),
    IsVendita BOOLEAN DEFAULT FALSE,
    PrezzoVendita DECIMAL(10 , 2 ) NOT NULL,
    Stock INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COMPOSIZIONE_PROG (
    ID_Programma INT,
    ID_Prodotto INT,
    QtaUtilizzata DECIMAL(5 , 2 ),
    PRIMARY KEY (ID_Programma , ID_Prodotto),
    FOREIGN KEY (ID_Programma)
        REFERENCES PROGRAMMI (ID_Programma)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Prodotto)
        REFERENCES PRODOTTI (ID_Prodotto)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PRENOTAZIONI (
    ID_Prenotazione INT AUTO_INCREMENT PRIMARY KEY,
    DataOra DATETIME NOT NULL,
    ID_Cliente INT,
    ID_Impianto INT,
    ID_Programma INT,
    Targa VARCHAR(10),
    Stato ENUM('CONFERMATA', 'COMPLETATA', 'CANCELLATA') DEFAULT 'CONFERMATA',
    FOREIGN KEY (ID_Cliente)
        REFERENCES CLIENTI (ID_Cliente),
    FOREIGN KEY (ID_Impianto)
        REFERENCES IMPIANTI (ID_Impianto),
    FOREIGN KEY (ID_Programma)
        REFERENCES PROGRAMMI (ID_Programma),
    FOREIGN KEY (Targa)
        REFERENCES VEICOLI (Targa)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS MANUTENZIONI (
    ID_Manutenzione INT AUTO_INCREMENT PRIMARY KEY,
    DataIntervento DATE,
    Descrizione TEXT,
    Costo DECIMAL(10 , 2 ),
    ID_Impianto INT,
    FOREIGN KEY (ID_Impianto)
        REFERENCES IMPIANTI (ID_Impianto)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CONSUMI_SEDE (
    ID_Consumo INT AUTO_INCREMENT PRIMARY KEY,
    DataLettura DATE NOT NULL,
    Acqua_Mc DECIMAL(10, 2) NOT NULL,
    Elettricita_Kwh DECIMAL(10, 2) NOT NULL,
    ID_Sede INT,
    FOREIGN KEY (ID_Sede) REFERENCES SEDI(ID_Sede) ON DELETE CASCADE ON UPDATE CASCADE
    );